/* eslint-disable */
// Generated by scripts/sync-risk-assets.mjs from the dashboard models.
export const bitcoinSnapshot = (() => {
const GENESIS = new Date('2009-01-03T00:00:00Z').getTime();
const WINDOW = 1460;
const MIN_REGRESSION_OBSERVATIONS = 30;
const ENV_UPPER_A = 4.6;
const ENV_UPPER_B = -1.10;
const ENV_LOWER = -0.45;
const ENV_MIN_MAX = 0.05;
const STRUCTURAL_RISK_FLOOR = 0.005;
const FAIR_VALUE_PROJECTION_SUPPLY = 20.8e6;
const FAIR_VALUE_LONG_RUN_GROWTH = 0.06;
const FAIR_VALUE_GOLD_GROWTH = 0.052;
const FAIR_VALUE_GOLD_ANCHOR_MS = Date.UTC(2025, 11, 31);
const FAIR_VALUE_DAMPENING_POWER = 2;
const FAIR_VALUE_DAYS_PER_YEAR = 365.2425;
const FAIR_VALUE_PROJECTION_END_MS = Date.UTC(2040, 11, 1);
function buildDataset(rawData) {
  const pts = rawData.map(([ds, p]) => {
    const ms = new Date(ds + 'T00:00:00Z').getTime();
    const days = (ms - GENESIS) / 864e5;
    return { date: ds, price: p, days, logDays: Math.log10(days), logPrice: Math.log10(p) };
  }).filter(p => p.days > 0 && p.price > 0);

  const n = pts.length;
  function fitRegression(endExclusive) {
    let sx=0,sy=0,sxy=0,sxx=0;
    for (let i=0; i<endExclusive; i++) {
      const p = pts[i];
      sx+=p.logDays; sy+=p.logPrice; sxy+=p.logDays*p.logPrice; sxx+=p.logDays*p.logDays;
    }
    const count = endExclusive;
    const slope = (count*sxy - sx*sy) / (count*sxx - sx*sx);
    const intercept = (sy - slope*sx) / count;
    return { slope, intercept };
  }
  const { slope, intercept } = fitRegression(n);

  pts.forEach((p, i) => {
    const asOf = fitRegression(Math.max(MIN_REGRESSION_OBSERVATIONS, i + 1));
    p.trendLogPrice = slope * p.logDays + intercept;
    p.trendPrice = Math.pow(10, p.trendLogPrice);
    p.regLogPrice = asOf.slope * p.logDays + asOf.intercept;
    p.regPrice = Math.pow(10, p.regLogPrice);
    p.residual = p.logPrice - p.regLogPrice;
    p.riskMM = structuralRiskForResidual(p.residual, p.logDays);
  });

  // Prior-window rolling Z-score. The current point is compared with the
  // previous window, so historical risk readings do not use the current close
  // to set their own momentum baseline.
  const residuals = pts.map(p => p.residual);
  let rSum=0, rSumSq=0;
  for (let i=0; i<n; i++) {
    const cnt = Math.min(i, WINDOW);
    if (cnt >= 180) {
      const mean = rSum/cnt;
      const vari = Math.max(0.0001, rSumSq/cnt - mean*mean);
      const std = Math.sqrt(vari);
      const z = (residuals[i]-mean)/std;
      pts[i].riskZS = normCdf(z);
      pts[i].rollMean = mean;
      pts[i].rollStd = std;
    } else {
      pts[i].riskZS = 0.5;
      pts[i].rollMean = 0;
      pts[i].rollStd = 0.1;
    }
    rSum += residuals[i]; rSumSq += residuals[i]*residuals[i];
    if (i >= WINDOW) { rSum -= residuals[i-WINDOW]; rSumSq -= residuals[i-WINDOW]*residuals[i-WINDOW]; }
  }

  pts.forEach(p => {
    p.riskCombo = Math.sqrt(p.riskMM * p.riskZS);
  });

  return { pts: pts.slice(MIN_REGRESSION_OBSERVATIONS - 1), slope, intercept };
}
function normCdf(z) {
  const t = 1.0 / (1.0 + 0.2316419 * Math.abs(z));
  const d = 0.3989422804 * Math.exp(-z*z/2);
  const p = d*t*(0.3193815 + t*(-0.3565638 + t*(1.781478 + t*(-1.8212560 + t*1.330274))));
  return z > 0 ? 1-p : p;
}
function structuralRiskForResidual(residual, logDays) {
  const envMax = Math.max(ENV_MIN_MAX, ENV_UPPER_A + ENV_UPPER_B * logDays);
  const structuralRaw = (residual - ENV_LOWER) / (envMax - ENV_LOWER);
  return Math.min(1, Math.max(STRUCTURAL_RISK_FLOOR, structuralRaw));
}
return raw => {
  if (raw.length < MIN_REGRESSION_OBSERVATIONS) throw new Error("Insufficient Bitcoin history");
  const { pts } = buildDataset(raw);
  const point = pts[pts.length - 1];
  return { date: point.date, price: point.price, risk: point.riskCombo };
};
})();
export const spySnapshot = (() => {
function upperBound(values, target) {
  let lo = 0, hi = values.length;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (values[mid] <= target) lo = mid + 1; else hi = mid;
  }
  return lo;
}
function assignTrailingPercentiles(pts, valueKey, outputKey) {
  const valid = pts.filter(p => Number.isFinite(p[valueKey]));
  const coordinates = Array.from(new Set(valid.map(p => p[valueKey]))).sort((a,b) => a-b);
  const bit = new Int32Array(coordinates.length + 1);
  const add = (idx, delta) => {
    for (let i = idx + 1; i < bit.length; i += i & -i) bit[i] += delta;
  };
  const sum = idx => {
    let total = 0;
    for (let i = idx; i > 0; i -= i & -i) total += bit[i];
    return total;
  };
  const windowMs = 20 * 365.25 * 864e5;
  let left = 0;
  valid.forEach((p, i) => {
    const cutoff = p.ms - windowMs;
    while (left < i && valid[left].ms < cutoff) {
      add(upperBound(coordinates, valid[left][valueKey]) - 1, -1);
      left++;
    }
    add(upperBound(coordinates, p[valueKey]) - 1, 1);
    const count = i - left + 1;
    p[outputKey] = sum(upperBound(coordinates, p[valueKey])) / count;
  });
}
function buildDataset(rawSPY, vixMap) {
  const pts = rawSPY.map(([ds, price, totalReturnIndex]) => ({
    totalReturnIndex,
    date: ds,
    price,
    ms: new Date(ds + 'T00:00:00Z').getTime(),
    vix: vixMap[ds] || null
  })).filter(p => p.price > 0);

  // A weekly reading becomes available in the following calendar week.
  // Apply this same conservative policy to every historical prefix.
  const weekly = [];
  const weekKey = p => {
    const d = new Date(p.ms);
    const daysFromMonday = (d.getUTCDay() + 6) % 7;
    d.setUTCDate(d.getUTCDate() - daysFromMonday);
    return d.toISOString().slice(0,10);
  };
  let activeWeek = null;
  let activeWeeklyClose = null;
  pts.forEach(p => {
    const key = weekKey(p);
    if (activeWeek !== null && key !== activeWeek) {
      weekly.push(activeWeeklyClose);
    }
    activeWeek = key;
    activeWeeklyClose = { date: p.date, ms: p.ms, price: p.price };
  });
  if (activeWeeklyClose) weekly.push(activeWeeklyClose);

  // 200-week moving average and causal trailing percentile, both calculated
  // strictly from weekly observations.
  let weeklySum = 0;
  weekly.forEach((p, i) => {
    weeklySum += p.price;
    if (i >= 200) weeklySum -= weekly[i - 200].price;
    if (i >= 199) {
      p.ma200W = weeklySum / 200;
      p.dev200W = Math.log(p.price / p.ma200W);
    }
  });
  assignTrailingPercentiles(weekly, 'dev200W', 'risk200W');

  // Use only prior calendar weeks, even on Fridays. This avoids provisional
  // signals that disappear when another observation arrives.
  let weeklyIdx = 0;
  let latestWeekly = null;
  pts.forEach(p => {
    while (weeklyIdx < weekly.length && weekKey(weekly[weeklyIdx]) < weekKey(p)) {
      latestWeekly = weekly[weeklyIdx++];
    }
    if (latestWeekly && Number.isFinite(latestWeekly.risk200W)) {
      p.signalWeekMs = latestWeekly.ms;
      p.ma200W = latestWeekly.ma200W;
      p.dev200W = latestWeekly.dev200W;
      p.risk200W = latestWeekly.risk200W;
      p.riskCombo = latestWeekly.risk200W;
    } else {
      p.riskCombo = 0.5;
      p.modelWarmup = true;
    }
  });

  let peak = 0;
  pts.forEach(p => {
    peak = Math.max(peak, p.price);
    p.drawdown = p.price / peak - 1;
  });

  return { pts, weekly };
}
return raw => {
  const { pts } = buildDataset(raw, {});
  const point = pts[pts.length - 1];
  if (!point || point.modelWarmup || !Number.isFinite(point.riskCombo)) throw new Error("Insufficient SPY history");
  return { date: point.date, price: point.price, risk: point.riskCombo };
};
})();
